# Este SÍ es el contenido para .github/workflows/firebase-hosting-merge.yml

name: Deploy to Firebase Hosting on Merge
on:
  push:
    branches:
      - main  # O 'master' o tu rama principal
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # ⭐️ CORRECCIÓN: Añadimos los pasos para construir el proyecto de la vidriera
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install and Build vidriera
        run: npm ci && npm run build
        working-directory: ./vidriera # ❗️ Le decimos que trabaje dentro de la carpeta 'vidriera'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JUEGOS_CUMPLE }}
          projectId: juegos-cumple
          channelId: live
          # Al no especificar 'channelId', se despliega en "live" (producción)